source_format: csv
target_format: json
record_type: disability
version: "1.0"
description: "Field mapping for disability insurance records from mainframe to modern system"

rules:
  - source_field: policy_number
    target_field: policyId
    transformation_type: direct
    validation:
      required: true
      pattern: "^[A-Z0-9]{6,12}$"
      min_length: 6
      max_length: 12

  - source_field: employee_id
    target_field: employeeId
    transformation_type: direct
    validation:
      required: true
      pattern: "^EMP[0-9]{6}$"

  - source_field: employer_id
    target_field: employerId
    transformation_type: direct
    validation:
      required: false
      pattern: "^EMP[0-9]{6}$"

  - source_field: effective_date
    target_field: effectiveDate
    transformation_type: date_format
    source_format: "%Y-%m-%d"
    target_format: "ISO8601"
    validation:
      required: true
      future_date: false

  - source_field: termination_date
    target_field: terminationDate
    transformation_type: date_format
    source_format: "%Y-%m-%d"
    target_format: "ISO8601"
    validation:
      required: false
      future_date: true

  - source_field: benefit_amount
    target_field: benefitAmount
    transformation_type: direct
    validation:
      required: false
      min_value: 0.0
      max_value: 1000000.0

  - source_field: premium_amount
    target_field: premiumAmount
    transformation_type: direct
    validation:
      required: false
      min_value: 0.0
      max_value: 50000.0

  - source_field: status
    target_field: policyStatus
    transformation_type: lookup
    lookup_table:
      active: "ACTIVE"
      inactive: "INACTIVE"
      pending: "PENDING"
      cancelled: "CANCELLED"
      suspended: "SUSPENDED"
      terminated: "TERMINATED"
    validation:
      required: true

  - source_field: coverage_type
    target_field: coverageType
    transformation_type: lookup
    lookup_table:
      STD: "SHORT_TERM_DISABILITY"
      LTD: "LONG_TERM_DISABILITY"
      BOTH: "BOTH"
    validation:
      required: true

  - source_field: waiting_period
    target_field: waitingPeriodDays
    transformation_type: calculated
    calculation_formula: "int(source_value)"  # Convert months to days
    validation:
      required: false
      min_value: 0
      max_value: 365

  - source_field: benefit_percentage
    target_field: benefitPercentage
    transformation_type: conditional
    condition: "float(source_value) if source_value and float(source_value) > 0 else 60.0"
    validation:
      required: false
      min_value: 0.0
      max_value: 100.0

  - source_field: max_benefit_duration
    target_field: maxBenefitDurationMonths
    transformation_type: direct
    validation:
      required: false
      min_value: 1
      max_value: 120

  - source_field: elimination_period
    target_field: eliminationPeriodDays
    transformation_type: calculated
    calculation_formula: "int(source_value)"  # Convert weeks to days
    validation:
      required: false
      min_value: 0
      max_value: 365

  - source_field: pre_existing_condition
    target_field: preExistingCondition
    transformation_type: lookup
    lookup_table:
      yes: "true"
      no: "false"
      Y: "true"
      N: "false"
    validation:
      required: false

  - source_field: occupation_class
    target_field: occupationClass
    transformation_type: direct
    validation:
      required: false
      pattern: "^[A-D]$"

  - source_field: created_date
    target_field: metadata.createdAt
    transformation_type: date_format
    source_format: "%Y-%m-%d %H:%M:%S"
    target_format: "ISO8601"
    validation:
      required: false

  - source_field: last_modified
    target_field: metadata.updatedAt
    transformation_type: date_format
    source_format: "%Y-%m-%d %H:%M:%S"
    target_format: "ISO8601"
    validation:
      required: false
