source_format: csv
target_format: json
record_type: customer_data
version: "1.0"
description: "Field mapping for customer data records from legacy system to modern platform"

rules:
  - source_field: customer_id
    target_field: customerId
    transformation_type: direct
    validation:
      required: true
      pattern: "^[A-Z0-9]{6,12}$"
      min_length: 6
      max_length: 12

  - source_field: user_id
    target_field: userId
    transformation_type: direct
    validation:
      required: true
      pattern: "^USR[0-9]{6}$"

  - source_field: company_id
    target_field: companyId
    transformation_type: direct
    validation:
      required: false
      pattern: "^COMP[0-9]{6}$"

  - source_field: registration_date
    target_field: registrationDate
    transformation_type: date_format
    source_format: "%Y-%m-%d"
    target_format: "ISO8601"
    validation:
      required: true
      future_date: false

  - source_field: last_login_date
    target_field: lastLoginDate
    transformation_type: date_format
    source_format: "%Y-%m-%d"
    target_format: "ISO8601"
    validation:
      required: false
      future_date: true

  - source_field: account_balance
    target_field: accountBalance
    transformation_type: direct
    validation:
      required: false
      min_value: 0.0
      max_value: 1000000.0

  - source_field: subscription_amount
    target_field: subscriptionAmount
    transformation_type: direct
    validation:
      required: false
      min_value: 0.0
      max_value: 50000.0

  - source_field: status
    target_field: accountStatus
    transformation_type: lookup
    lookup_table:
      active: "ACTIVE"
      inactive: "INACTIVE"
      pending: "PENDING"
      suspended: "SUSPENDED"
      terminated: "TERMINATED"
    validation:
      required: true

  - source_field: subscription_type
    target_field: subscriptionType
    transformation_type: lookup
    lookup_table:
      BASIC: "BASIC"
      PREMIUM: "PREMIUM"
      ENTERPRISE: "ENTERPRISE"
    validation:
      required: true

  - source_field: trial_period
    target_field: trialPeriodDays
    transformation_type: calculated
    calculation_formula: "int(source_value) * 30"  # Convert months to days
    validation:
      required: false
      min_value: 0
      max_value: 365

  - source_field: discount_percentage
    target_field: discountPercentage
    transformation_type: conditional
    condition: "if source_value and float(source_value) > 0 else 0.0"
    validation:
      required: false
      min_value: 0.0
      max_value: 100.0

  - source_field: email
    target_field: emailAddress
    transformation_type: direct
    validation:
      required: true
      pattern: "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$"

  - source_field: phone
    target_field: phoneNumber
    transformation_type: direct
    validation:
      required: false
      pattern: "^[0-9]{10,15}$"

  - source_field: address_line1
    target_field: address.street1
    transformation_type: direct
    validation:
      required: false
      max_length: 100

  - source_field: address_line2
    target_field: address.street2
    transformation_type: direct
    validation:
      required: false
      max_length: 100

  - source_field: city
    target_field: address.city
    transformation_type: direct
    validation:
      required: false
      max_length: 50

  - source_field: state
    target_field: address.state
    transformation_type: direct
    validation:
      required: false
      max_length: 2

  - source_field: zip_code
    target_field: address.zipCode
    transformation_type: direct
    validation:
      required: false
      pattern: "^[0-9]{5}(-[0-9]{4})?$"

  - source_field: country
    target_field: address.country
    transformation_type: direct
    validation:
      required: false
      max_length: 50

  - source_field: created_timestamp
    target_field: metadata.createdAt
    transformation_type: date_format
    source_format: "%Y-%m-%d %H:%M:%S"
    target_format: "ISO8601"
    validation:
      required: false

  - source_field: updated_timestamp
    target_field: metadata.updatedAt
    transformation_type: date_format
    source_format: "%Y-%m-%d %H:%M:%S"
    target_format: "ISO8601"
    validation:
      required: false

  - source_field: source_system
    target_field: metadata.sourceSystem
    transformation_type: direct
    validation:
      required: false

  - source_field: migration_batch
    target_field: metadata.migrationBatch
    transformation_type: direct
    validation:
      required: false
